# Generated by Django 6.0 on 2026-06-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/thumbnail', verbose_name='Thumbnail'),
        ),
    ]
