version: '3.9'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_socialnet:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
    networks:
      - socialnet-network

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - ./dotenv_files/.env
    networks:
    - socialnet-network
    depends_on:
      - db

volumes:
  db_socialnet:

networks:
  socialnet-network: