services:
  db:
    image: postgres:17
    volumes:
      - db_socialnet:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
    networks:
      - socialnet-network

  web:
    image: rafaelrodriguess/social-network
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/data/web/static
      - media_volume:/data/web/media
    env_file:
      - ./dotenv_files/.env
    networks:
      - socialnet-network
    depends_on:
      - db

networks:
  socialnet-network:

volumes:
  db_socialnet:
  static_volume:
  media_volume:
