version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - db_socialnet:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
    networks:
      - socialnet-network

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - media_volume:/data/web/media
      - static_volume:/data/web/static
    env_file:
      - ./dotenv_files/.env
    networks:
    - socialnet-network
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  db_socialnet:
  media_volume:
  static_volume:

networks:
  socialnet-network: