version: '3.9'

services:
  db:
    image: postgres:17
    volumes:
      - db_socialnet:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
    networks:
      - socialnet-network

  web:
    image: rafaelrodriguess/social-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/data/web/static
      - media_volume:/data/web/media
    env_file:
      - ./dotenv_files/.env
    networks:
      - socialnet-network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/data/web/static
      - media_volume:/data/web/media
    ports:
      - "80:80"
    networks:
      - socialnet-network
    depends_on:
      - web

networks:
  socialnet-network:
    driver: overlay

volumes:
  db_socialnet:
  static_volume:
  media_volume:
