# Generated by Django 5.1.5 on 2025-02-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publication_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='publications/images/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
